name: 'xtream AI-based PR Reviewer'
description: 'xtream AI-based PR Reviewer'
branding:
  icon: 'git-merge'
  color: 'blue'
author: 'xtream srl'
inputs:
  openai_api_base_url:
    required: false
    description: 'The url of the openai api interface.'
    default: 'https://api.openai.com/v1'
  openai_model:
    required: false
    description: 'GPT Model to use'
    default: 'gpt-3.5-turbo'
  openai_model_temperature:
    required: false
    description: 'Temperature for GPT model'
    default: '0.05'
  openai_concurrency_limit:
    required: false
    description: 'How many concurrent API calls to make to OpenAI servers?'
    default: '6'
  github_concurrency_limit:
    required: false
    description: 'How many concurrent API calls to make to GitHub?'
    default: '6'
runs:
  using: 'composite'
  steps:
    - name: Setup Node 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: ai-pr-review action
      id: ai-pr-review
      run: node ${{ github.action_path }}/dist/index.js
      shell: ${{ (runner.os == 'Windows' && 'pwsh') || 'bash' }}
      env:
        OPENAI_API_BASE_URL: ${{ inputs.openai_api_base_url }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
        OPENAI_MODEL_TEMPERATURE: ${{ inputs.openai_model_temperature }}
        OPENAI_CONCURRENCY_LIMIT: ${{ inputs.openai_concurrency_limit }}
        GITHUB_CONCURRENCY_LIMIT: ${{ inputs.github_concurrency_limit }}
